version: "3"
services:
  mediator:
    build: .
    container_name: mediator
    ports:
      - "22000:6000"
    environment:
      - "OPENHIM_USERNAME=${OPENHIM_USERNAME}"
      - "OPENHIM_PASSWORD=${OPENHIM_PASSWORD}"
      - "OPENHIM_API_URL=${OPENHIM_API_URL}"