name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run:  touch .env            
              echo OPENHIM_USERNAME = ${{ secrets.OPENHIM_USERNAME }} >> .env
              echo OPENHIM_PASSWORD = ${{ secrets.OPENHIM_PASSWORD }} >> .env
              echo OPENHIM_API_URL =  ${{ secrets.OPENHIM_API_URL }} >> .env
              echo PORT = ${{ secrets.PORT }} >> .env
              echo CLIENT_REGISTRY_URL = ${{ secrets.CLIENT_REGISTRY_URL }} >> .env
      - run: npm ci
      - run: npm test
